Repository boostcampwm-2021/android07-notto, pull requests merged in 2021-11, with the labels that each got.

#36 Revert "[demo_week2] Bottom Navigation 이름 변경"
  app/src/main/java/com/gojol/notto/MainActivity.kt
  app/src/main/java/com/gojol/notto/ui/dashboard/DashboardFragment.kt
  app/src/main/java/com/gojol/notto/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/com/gojol/notto/ui/notifications/NotificationsFragment.kt
  app/src/main/java/com/gojol/notto/ui/notifications/NotificationsViewModel.kt
  app/src/main/res/drawable/ic_bottom_option.xml
  app/src/main/res/drawable/ic_bottom_popular.xml
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: ✏review

#47 [demo_week2] 홈 화면 어댑터 구현
  app/build.gradle
  app/src/main/java/com/gojol/notto/ui/home/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/TodoAdapter.kt
  app/src/main/res/drawable/ic_more_vert.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_label.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/layout/item_monthly_calendar.xml
  app/src/main/res/layout/item_todo.xml
  build.gradle
Labels: ✅approval, 🖥feature

#54 [demo_week2] 라벨 관련 데이터타입 추가, 라벨 필터링 로직 구현
  app/src/main/java/com/gojol/notto/ui/home/Dummy.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelWithCheck.kt
Labels: ✅approval, 🖥feature

#51 [demo_week2] BindingAdapter 추가, 스와이프 기능 일부 구현
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/data/BindingData.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/ui/home/BindAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/Dummy.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelWithCheck.kt
  app/src/main/java/com/gojol/notto/ui/home/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/utils/ItemTouchHelperListener.kt
  app/src/main/java/com/gojol/notto/ui/home/utils/TodoItemTouchCallback.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_label.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/layout/item_monthly_calendar.xml
  app/src/main/res/layout/item_todo.xml
  build.gradle
  settings.gradle
Labels: ✏review, 🖥feature

#57 #3 [fix] home 관련 레이아웃 디자인 수정
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_label.xml
  app/src/main/res/layout/item_label_list.xml
Labels: ✅approval, 🖥feature

#59 [demo_week2] SplashActivity 추가
  app/src/main/java/com/gojol/notto/ui/MainActivity.kt
  app/src/main/java/com/gojol/notto/ui/SplashActivity.kt
  app/src/main/res/drawable/notto_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: ✏review

#62 [demo_week2] 캘린더 월 표시, 앱 아이콘 변경
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/gojol/notto/ui/MainActivity.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/utils/TodoItemTouchCallback.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/item_monthly_calendar.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: ✅approval

#65 [demo_week2] 발표용 - 더미 데이터 생성 및 사소한 디자인 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/res/layout/item_todo.xml
Labels: ✅approval

#66 [demo_week2] 패키지 관리 - 어댑터 패키지 및 data 패키지 관리
  app/src/main/java/com/gojol/notto/model/data/BindingData.kt
  app/src/main/java/com/gojol/notto/model/data/LabelWithCheck.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/BindAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/ItemTouchHelperListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
Labels: ✅approval

#68 [demo_week2] 아이콘 수정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/ic_notto_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_notto_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_notto_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/ic_notto_launcher_background.xml
Labels: ✅approval

#72 [demo_week2] Not Todo 목록 스와이프 관련 버그 수정 및 코드 개선
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
Labels: 🐞bug, ✏review

#75 [demo_week3] Todo 관련 리팩토링, 스와이프 취소 구현, 텍스트 색상과 크기 변경
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/ItemTouchHelperListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
  app/src/main/res/layout/item_todo.xml
Labels: ✏review, 🖥feature

#76 [demo_week3] HomeViewModel, HomeFragment 리팩토링
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/data/BindingData.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/BindAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/res/layout/fragment_home.xml
Labels: ✏review

#77 [demo_week3] FakeTodoLabelRepository 구현
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
Labels: ✅approval, 🖥feature

#81 [demo_week3] Home 화면에 Todo 추가 버튼 추가
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/dimens.xml
Labels: ✅approval, 🖥feature

#87 [demo_week3] label 리팩토링
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelAdapter.kt
  app/src/main/res/color/bg_chip_normal.xml
  app/src/main/res/layout/item_label.xml
Labels: ✅approval

#92 [demo_week3] 캘린더 기본 기능 디자인 구현
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/GridSpacingDecoration.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/drawable/ic_calendar_collapse.xml
  app/src/main/res/drawable/ic_calendar_expand.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature

#90 [demo_week3] Todo 편집 화면 다이얼로그 레이아웃 구성
  app/build.gradle
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoAlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoBaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoBaseDialogImpl.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoSetTimeDialog.kt
  app/src/main/res/color/bg_radio_button_normal.xml
  app/src/main/res/drawable/bg_dialog.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_todo_alarm_period.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/dialog_todo_set_time.xml
  app/src/main/res/layout/item_dialog_bottom_button.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🖥feature

#93 [demo_week3] 홈 화면 버그 수정
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoBaseDialogImpl.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_todo_alarm_period.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/dialog_todo_set_time.xml
  app/src/main/res/layout/item_dialog_bottom_button.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🐞bug, ✏review

#95 [demo_week3] Todo 편집 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/model/data/RepeatType.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/todo/SelectedLabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/drawable/bg_todo_edit_button.xml
  app/src/main/res/drawable/bg_todo_edit_label_add_button.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_time_filled.xml
  app/src/main/res/drawable/ic_visibility_outline.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/menu/todo_edit_top_app_bar.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🖥feature

#98 [demo_week3] DB 구조 변경, 홈화면과 투두편집 화면에 DB 적용
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/data/TodoWithTodayDailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
  app/src/main/java/com/gojol/notto/model/database/label/Label.kt
  app/src/main/java/com/gojol/notto/model/database/todo/DailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Keyword.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/database/todo/TodoWithDailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/todo/TodoWithKeyword.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/DailyTodoWithTodoAndLabel.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/ItemTouchHelperListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/layout/item_todo.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: ✅approval, 🖥feature

#96 [demo_week3] 라벨 편집 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/DeleteLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/ItemTouchCallback.kt
  app/src/main/res/color/bg_bottom_normal.xml
  app/src/main/res/drawable/bg_edit_label.xml
  app/src/main/res/drawable/edit_label_create.xml
  app/src/main/res/drawable/edit_label_delete.xml
  app/src/main/res/drawable/ic_edit_label_move.xml
  app/src/main/res/layout/activity_edit_label.xml
  app/src/main/res/layout/dialog_fragment_delete_label.xml
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/layout/item_edit_label.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/menu/edit_label_toolbar_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✅approval, 🖥feature

#97 [demo_week3] FakeRepository 싱글톤 수정, Todo 편집 화면 insertTodo 수정 및 데이터 바인딩 적용
  app/src/main/java/com/gojol/notto/common/Event.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: ✅approval, 🖥feature

#105 [demo_week3] label 패키지 정리
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/util/ItemTouchCallback.kt
  app/src/main/res/layout/dialog_fragment_delete_label.xml
  app/src/main/res/layout/dialog_fragment_edit_label.xml
Labels: ✅approval

#106 [demo_week3] Not Todo 다이얼로그 기능 구현 및 연결
  app/src/main/ic_launcher_example-playstore.png
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoAlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialogImpl.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/util/Event.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/drawable-v24/ic_launcher_example_foreground.xml
  app/src/main/res/drawable/ic_launcher_example_background.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_todo_alarm_period.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/dialog_todo_set_time.xml
  app/src/main/res/layout/item_dialog_bottom_button.xml
Labels: ✏review, 🖥feature

#110 [demo_week3] fakeRepository 제거
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
Labels: ✅approval

#113 [demo_week3] 폰트 적용, 투두 편집화면 디자인 수정
  app/src/main/res/color/switch_thumb.xml
  app/src/main/res/color/switch_track.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🎨design

#116 [demo_week3] Todo 편집 화면 - 편집 기능 구현
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
Labels: ✏review, 🖥feature

#117 [demo_week3] 라벨 편집 화면에서 '전체' 라벨 제외
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
Labels: ✅approval, 🖥feature

#118 [demo_week3] date 포멧 관련 버그 수정
  app/src/main/java/com/gojol/notto/util/Extensions.kt
Labels: 🐞bug, ✅approval

#120 [demo_week3] 라벨 초기화 코드 추가
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
Labels: 🐞bug, ✏review

#126 [demo_week3] 다이얼로그 구조 수정
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoAlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialogImpl.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/java/com/gojol/notto/util/TouchEvent.kt
  app/src/main/res/layout/dialog_base.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_todo_alarm_period.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/dialog_todo_set_time.xml
Labels: ✅approval, 🖥feature

#128 [demo_week4] stetho 적용
  app/build.gradle
  app/src/main/java/com/gojol/notto/NottoApplication.kt
Labels: ✅approval

#133 [demo_week4] 라벨 편집 화면 Dialog 버그 수정
  app/build.gradle
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
Labels: 🐞bug, ✅approval

#137 [demo_week4] 캘린더 날짜별 달성률과 선택한 날짜에 따른 투두 출력 구현
  app/src/main/java/com/gojol/notto/model/data/DateWithCountAndSelect.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/drawable/bg_calendar_day_circle.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
Labels: ✅approval, 🖥feature

#140 [demo_week4] 라벨 간격 맞춤
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/item_label.xml
  app/src/main/res/values/dimens.xml
Labels: ✏review, 🎨design

#139 [demo_week4] Todo 삭제 기능 구현
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature, 🎨design

#141 [demo_week4] 라벨 간격 버그 수정
  app/build.gradle
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/layout/item_label.xml
  app/src/main/res/values/strings.xml
Labels: 🐞bug, ✏review

#142 [demo_week4] 캘린더와 홈 Fragment 간의 데이터 통신 구현 (깜박임 현상 해결)
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
Labels: 🐞bug, ✏review, 🖥feature

#143 [demo_week4] 투두 편집 화면 디자인 리팩토링
  app/src/main/java/com/gojol/notto/ui/todo/SelectedLabelAdapter.kt
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/layout/activity_edit_label.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/item_edit_todo_label.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🎨design

#132 [demo_week4] Option 화면 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/BootReceiver.kt
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/SharedPrefManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationManager.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationReceiver.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionFragment.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_expand_more.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: ✅approval, 🖥feature, 🎨design

#144 [demo_week4] 스크롤, 스와이프 시 바깥 영역을 사용하도록 변경
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/layout/item_todo.xml
  app/src/main/res/values/dimens.xml
Labels: ✅approval, 🎨design

#145 [demo_week4] 캘린더 디자인 수정 및 투두 스와이프 / 라벨 위치 변경 시 이동 반경 제한
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/util/GridSpacingDecoration.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoItemTouchCallback.kt
  app/src/main/java/com/gojol/notto/ui/label/util/ItemTouchCallback.kt
  app/src/main/res/drawable/ic_calendar_collapse.xml
  app/src/main/res/drawable/ic_calendar_expand.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_label_list.xml
Labels: ✏review, 🎨design

#146 [demo_week4] 푸시 알림 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/BootReceiver.kt
  app/src/main/java/com/gojol/notto/NottoApplication.kt
  app/src/main/java/com/gojol/notto/di/TodoAlarmModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/AddDailyTodoWorker.kt
  app/src/main/java/com/gojol/notto/util/AddTodoAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/java/com/gojol/notto/util/FailButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/HiltBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/TodoPushBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoRebootBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
  app/src/main/res/drawable/ic_check_box_24.xml
  app/src/main/res/drawable/ic_close_box_24.xml
  app/src/main/res/layout/notification_todo.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature

#138 [develop] 인기 키워드 화면 구현
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/values/strings.xml
  build.gradle
  nottokeyword/.gitignore
  nottokeyword/build.gradle
  nottokeyword/consumer-rules.pro
  nottokeyword/proguard-rules.pro
  nottokeyword/src/androidTest/java/com/example/nottokeyword/ExampleInstrumentedTest.kt
  nottokeyword/src/main/AndroidManifest.xml
  nottokeyword/src/main/java/com/example/nottokeyword/FirebaseDB.kt
  nottokeyword/src/main/java/com/example/nottokeyword/Keyword.kt
  nottokeyword/src/test/java/com/example/nottokeyword/ExampleUnitTest.kt
  settings.gradle
Labels: ✏review, 🖥feature, 🎨design

#148 [develop] 캘린더 관련 버그 로직 수정
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
Labels: 🐞bug, ✅approval

#149 [demo_week4] 캘린더 관련 로직 수정
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
Labels: ✅approval

#151 [demo_week4] gitignore에 firebase key 파일 추가, db migration 설정
  .gitignore
  app/src/main/java/com/gojol/notto/di/TodoLabelDatabaseModule.kt
  app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
Labels: ✅approval

#154 [develop] Todo 삭제, 업데이트 수정
  app/src/main/java/com/gojol/notto/common/Event.kt
  app/src/main/java/com/gojol/notto/model/database/todo/DailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialogImpl.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/TouchEvent.kt
  app/src/main/res/layout/activity_todo_edit.xml
Labels: ✏review, 🖥feature

#156 [demo_week4] Todo 푸시 알림 리팩토링, Todo 삭제 및 업데이트 수정
  app/src/main/java/com/gojol/notto/common/Event.kt
  app/src/main/java/com/gojol/notto/model/database/todo/DailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoBaseDialogImpl.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/TodoPushBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TouchEvent.kt
  app/src/main/res/layout/activity_todo_edit.xml
Labels: ✅approval, 🖥feature

#157 [develop] 스플래쉬 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: ✅approval, 🖥feature, 🎨design

#158 [demo_week4] 스플래쉬 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: ✅approval, 🖥feature, 🎨design, 🚖demo

#159 [develop] db 시간, 날짜관련 데이터 타입 변경 및 관련 로직 수정
  app/build.gradle
  app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
  app/src/main/java/com/gojol/notto/model/database/converter/Converter.kt
  app/src/main/java/com/gojol/notto/model/database/todo/DailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/AddDailyTodoWorker.kt
  app/src/main/java/com/gojol/notto/util/AddTodoAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/java/com/gojol/notto/util/FailButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_monthly_calendar.xml
Labels: ✏review, 🖥feature, 🛩develop

#160 [demo_week5] db 시간, 날짜관련 데이터 타입 변경 및 관련 로직 수정
  app/build.gradle
  app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
  app/src/main/java/com/gojol/notto/model/database/converter/Converter.kt
  app/src/main/java/com/gojol/notto/model/database/todo/DailyTodo.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/AddDailyTodoWorker.kt
  app/src/main/java/com/gojol/notto/util/AddTodoAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/java/com/gojol/notto/util/FailButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_monthly_calendar.xml
Labels: ✅approval, 🖥feature, 🚖demo

#161 [develop] 라벨 편집 리팩토링
  app/build.gradle
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/database/label/Label.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
Labels: ✅approval, 🛩develop

#162 [demo_week5] 라벨 편집 리팩토링
  app/build.gradle
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/database/label/Label.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
Labels: ✏review, 🚖demo

#163 [develop] todo 푸시 알림 리팩토링
  app/src/main/java/com/gojol/notto/NottoApplication.kt
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/di/TodoAlarmModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/splash/SplashActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/AddDailyTodoWorker.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/java/com/gojol/notto/util/FailButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/RebootAddAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/TodoPushBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoRebootBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
Labels: ✏review, 🛩develop

#166 [demo_week5] todo 푸시 알림 리팩토링
  app/src/main/java/com/gojol/notto/NottoApplication.kt
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/di/TodoAlarmModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/splash/SplashActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/AddDailyTodoWorker.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/java/com/gojol/notto/util/FailButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/RebootAddAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/java/com/gojol/notto/util/TodoPushBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoRebootBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
Labels: ✏review, 🚖demo

#165 [develop] Option 화면 리팩토링
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/SharedPrefManager.kt
  app/src/main/java/com/gojol/notto/model/SharedPrefManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/ui/option/DayAlarmManager.kt
  app/src/main/java/com/gojol/notto/ui/option/DayAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationManager.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationReceiver.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionFragment.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
  app/src/main/java/com/gojol/notto/util/TodoRebootBroadcastReceiver.kt
Labels: ✅approval, 🛩develop

#168 [demo_week5] Option 화면 리팩토링
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/SharedPrefManager.kt
  app/src/main/java/com/gojol/notto/model/SharedPrefManagerImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/ui/option/DayAlarmManager.kt
  app/src/main/java/com/gojol/notto/ui/option/DayAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationManager.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationReceiver.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionFragment.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
  app/src/main/java/com/gojol/notto/util/TodoRebootBroadcastReceiver.kt
Labels: ✅approval, 🚖demo

#167 [develop] 캘린더 리팩토링
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/model/data/DailyTodoSuccess.kt
  app/src/main/java/com/gojol/notto/model/data/DateWithCountAndSelect.kt
  app/src/main/java/com/gojol/notto/model/data/DayWithSuccessLevelAndSelect.kt
  app/src/main/java/com/gojol/notto/model/data/MonthlyCalendar.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
Labels: 🐞bug, ✏review, 🖥feature, 🎨design, 🛩develop

#169 [demo_week5] 캘린더 리팩토링
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/model/data/DailyTodoSuccess.kt
  app/src/main/java/com/gojol/notto/model/data/DateWithCountAndSelect.kt
  app/src/main/java/com/gojol/notto/model/data/DayWithSuccessLevelAndSelect.kt
  app/src/main/java/com/gojol/notto/model/data/MonthlyCalendar.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarViewPagerAdapter.kt
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
Labels: 🐞bug, ✅approval, 🖥feature, 🎨design, 🚖demo

#171 [develop] Todo 편집화면 리팩토링 및 디자인 수정
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/data/RepeatType.kt
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/model/data/todo/TodoWrapper.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/res/drawable/ic_today.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature, 🎨design, 🛩develop

#172 [demo_week5] Todo 편집화면 리팩토링 및 디자인 수정
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/common/Enums.kt
  app/src/main/java/com/gojol/notto/model/data/RepeatType.kt
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/model/data/todo/TodoWrapper.kt
  app/src/main/java/com/gojol/notto/model/database/todo/Todo.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialogViewModel.kt
  app/src/main/res/drawable/ic_today.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: ✅approval, 🖥feature, 🎨design, 🚖demo

#170 [develop] 다이얼로그 리팩토링
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/BaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/DialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/AlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/DeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeFinishDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeStartDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoAlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/AlarmPeriodDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/DeletionDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/RepeatTimeDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/RepeatTypeDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TimeFinishDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TimeStartDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialog.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_base.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_fragment_delete_label.xml
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/layout/dialog_todo_alarm_period.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/dialog_todo_time_finish.xml
  app/src/main/res/layout/dialog_todo_time_start.xml
  app/src/main/res/layout/item_dialog_bottom_button.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🛩develop

#174 [demo_week5] 다이얼로그 리팩토링
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/BaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/DialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/AlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/DeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeFinishDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeStartDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoAlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoDeletionDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoRepeatTypeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TodoSetTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/AlarmPeriodDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/DeletionDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/RepeatTimeDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/RepeatTypeDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TimeFinishDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TimeStartDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TodoBaseDialog.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_base.xml
  app/src/main/res/layout/dialog_deletion.xml
  app/src/main/res/layout/dialog_fragment_delete_label.xml
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/layout/dialog_todo_alarm_period.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_repeat_type.xml
  app/src/main/res/layout/dialog_todo_time_finish.xml
  app/src/main/res/layout/dialog_todo_time_start.xml
  app/src/main/res/layout/item_dialog_bottom_button.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🚖demo

#173 [develop] 홈화면 디자인 수정, db 버전 3으로 업그레이드
  app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/res/drawable/bg_calendar_success_level.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/layout/item_todo.xml
Labels: ✅approval, 🎨design, 🛩develop

#175 [demo_week5] 홈화면 디자인 수정, db 버전 3으로 업그레이드
  app/src/main/java/com/gojol/notto/model/database/TodoLabelDatabase.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/res/drawable/bg_calendar_success_level.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/layout/item_todo.xml
Labels: ✅approval, 🎨design, 🚖demo

#176 [develop] icon 디자인 수정
  app/src/main/ic_launcher_example-playstore.png
  app/src/main/ic_notto_launcher-playstore.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher_round.png
Labels: ✅approval, 🎨design, 🛩develop

#177 [demo_week5] icon 디자인 수정
  app/src/main/ic_launcher_example-playstore.png
  app/src/main/ic_notto_launcher-playstore.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_notto_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_notto_launcher_round.png
Labels: ✏review, 🎨design, 🚖demo

#178 [develop] timepicker 버그 수정
  app/src/main/res/layout/dialog_todo_time_finish.xml
  app/src/main/res/layout/dialog_todo_time_start.xml
Labels: 🐞bug, ✅approval, 🛩develop

#179 [demo_week5] timepicker 버그 수정
  app/src/main/res/layout/dialog_todo_time_finish.xml
  app/src/main/res/layout/dialog_todo_time_start.xml
Labels: ✅approval, 🚖demo

#181 [develop] swipe 깜빡임 버그 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
Labels: 🐞bug, ✅approval, 🛩develop

#183 [demo_week5] swipe 깜빡임 버그 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
Labels: 🐞bug, ✅approval, 🚖demo

#182 [develop] 라벨 편집 화면 버그 수정
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/util/ItemTouchCallback.kt
Labels: 🐞bug, ✅approval, 🛩develop

#184 [demo_week5] 라벨 편집 버그 수정
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/util/ItemTouchCallback.kt
Labels: 🐞bug, ✏review

#180 [develop] Todo 편집화면 내용 없을 때 처리 및 업데이트 버튼 눌렀을 때 다이얼로그 띄우기
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✅approval, 🖥feature, 🎨design, 🛩develop

#185 [demo_week5] Todo 편집화면 내용 없을 때 처리 및 업데이트 버튼 눌렀을 때 다이얼로그 띄우기
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✅approval, 🖥feature, 🎨design, 🚖demo

#186 [develop] 라벨 편집 팝업 메뉴 구현
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/util/EditLabelDialogBuilder.kt
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/menu/home_label_popup_menu.xml
Labels: ✏review, 🖥feature, 🎨design, 🛩develop

#187 [demo_week5] 라벨 편집 팝업 메뉴 구현
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelActivity.kt
  app/src/main/java/com/gojol/notto/util/EditLabelDialogBuilder.kt
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/menu/home_label_popup_menu.xml
Labels: ✅approval, 🖥feature, 🎨design, 🚖demo

#188 [develop] android 12v의 pending intent 오류 해결
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/option/DayAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/option/DayNotificationReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoPushBroadcastReceiver.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
Labels: 🐞bug, ✅approval, 🛩develop

#191 [develop] Todo 편집화면 기능 수정
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values-night/themes.xml
Labels: ✏review, 🖥feature, 🎨design, 🛩develop

#192 [demo_week5] Todo 편집화면 기능 수정
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values-night/themes.xml
Labels: ✏review, 🖥feature, 🎨design, 🚖demo

#190 [develop] README.md 수정
  README.md
Labels: 📃doc, ✅approval

#193 [demo_week5] README.md 수정
  README.md
Labels: 📃doc, ✏review, 🚖demo

#194 [develop] 다크 테마 구현
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/res/color/bg_bottom_night.xml
  app/src/main/res/drawable/bg_edit_label.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_time_start.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_edit_label.xml
  app/src/main/res/layout/item_edit_todo_label.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/menu/todo_edit_top_app_bar.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✏review, 🎨design

#195 [demo_week5] 다크 테마 구현
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/res/color/bg_bottom_night.xml
  app/src/main/res/drawable/bg_edit_label.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/layout/dialog_todo_repeat_time.xml
  app/src/main/res/layout/dialog_todo_time_start.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_edit_label.xml
  app/src/main/res/layout/item_edit_todo_label.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/menu/todo_edit_top_app_bar.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ✅approval, 🎨design, 🚖demo

#199 [develop] 라벨 수정 다이얼로그 버그 해결
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
Labels: 🐞bug, ✅approval, 🛩develop

#200 [demo_week5] 라벨 수정 다이얼로그 버그 해결
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
Labels: 🐞bug, ✅approval, 🚖demo

#201 [develop] Option 화면 하루 마무리 알림 설명 추가
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature, 🎨design, 🛩develop

#202 [demo_week5] Option 화면 하루 마무리 알림 설명 추가
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/values/strings.xml
Labels: ✅approval, 🖥feature, 🎨design, 🚖demo

#198 [develop] Todo 편집 화면 기능 추가
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature, 🛩develop

#203 [demo] Todo 편집화면 기능 추가
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/model/database/todolabel/TodoLabelDao.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/values/strings.xml
Labels: ✅approval, 🖥feature, 🎨design, 🛩develop

#197 [develop] 캘린더 오늘 버튼 추가, 인기화면 로딩 인디케이터와 네트워크 확인 추가, bottom nav 메뉴 선택 제한
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/model/data/DayWithSuccessLevelAndSelect.kt
  app/src/main/java/com/gojol/notto/ui/MainActivity.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🎨design, 🛩develop

#204 [demo_week5] 캘린더 오늘 버튼 추가, 인기화면 로딩 인디케이터와 네트워크 확인 추가, bottom nav 메뉴 선택 제한
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/model/data/DayWithSuccessLevelAndSelect.kt
  app/src/main/java/com/gojol/notto/ui/MainActivity.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✅approval, 🎨design, 🚖demo

#205 [develop] 캘린더 refresh, 날짜 select 로직 수정
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
Labels: ✏review, 🖥feature, 🛩develop

#206 [demo_week5] 캘린더 refresh, 날짜 select 로직 수정
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
Labels: ✅approval, 🖥feature, 🚖demo

#164 [develop] 인기 키워드 리팩토링
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/layout/item_label.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/menu/home_label_context_menu.xml
  nottokeyword/build.gradle
  nottokeyword/src/main/java/com/example/nottokeyword/FirebaseDB.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabase.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabaseImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordModule.kt
Labels: ✏review, 🛩develop

#210 [demo_week5] 인기 키워드 리팩토링
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/layout/item_label.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/menu/home_label_context_menu.xml
  nottokeyword/build.gradle
  nottokeyword/src/main/java/com/example/nottokeyword/FirebaseDB.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabase.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabaseImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordModule.kt
Labels: ✏review, 🚖demo

#211 [develop] 캘린더 다크모드 디자인 수정, 월별 데이터 로직 수정
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: ✅approval, 🖥feature, 🎨design, 🛩develop

#212 [demo_week5] 캘린더 다크모드 디자인 수정, 월별 데이터 로직 수정
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/ui/home/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/CalendarDayAdapter.kt
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: ✏review, 🖥feature, 🎨design, 🚖demo

#216 [develop] 캘린더 관련 오류 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/DayClickListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/MonthSwipeListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodayClickListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoSwipeListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/todo/ItemTouchHelperListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/todo/TodoItemTouchCallback.kt
Labels: 🐞bug, ✅approval, 🛩develop

#218 [demo_week6] 캘린더 관련 오류 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/TodoAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarViewModel.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/util/DayClickListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/MonthSwipeListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodayClickListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/TodoSwipeListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/todo/ItemTouchHelperListener.kt
  app/src/main/java/com/gojol/notto/ui/home/util/todo/TodoItemTouchCallback.kt
Labels: 🐞bug, ✅approval, 🚖demo

#219 [develop] 캘린더 fragment에서 캐스팅 오류 수정
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
Labels: 🐞bug, ✅approval, 🛩develop

#220 [demo_week6] 캘린더 fragment에서 캐스팅 오류 수정
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
Labels: 🐞bug, ✅approval, 🚖demo

#217 [develop] Option 화면 버그 수정 및 Contributors 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/network/GithubResponse.kt
  app/src/main/java/com/gojol/notto/network/GithubService.kt
  app/src/main/java/com/gojol/notto/ui/option/ContributorActivity.kt
  app/src/main/java/com/gojol/notto/ui/option/ContributorAdapter.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionFragment.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
  app/src/main/java/com/gojol/notto/util/NetworkState.kt
  app/src/main/res/layout/activity_contributor.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/layout/item_contributor.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🐞bug, ✅approval, 🖥feature, 🎨design, 🛩develop

#221 [demo_week6] Option 화면 버그 수정 및 Contributors 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/network/GithubResponse.kt
  app/src/main/java/com/gojol/notto/network/GithubService.kt
  app/src/main/java/com/gojol/notto/ui/option/ContributorActivity.kt
  app/src/main/java/com/gojol/notto/ui/option/ContributorAdapter.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionFragment.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
  app/src/main/java/com/gojol/notto/util/NetworkState.kt
  app/src/main/res/layout/activity_contributor.xml
  app/src/main/res/layout/fragment_option.xml
  app/src/main/res/layout/item_contributor.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🐞bug, ✅approval, 🖥feature, 🎨design, 🚖demo

#215 [develop] pull to refresh 구현
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/menu/popular_toolbar_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  nottokeyword/src/main/AndroidManifest.xml
  nottokeyword/src/main/java/com/example/nottokeyword/Constants.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabase.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabaseImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordModule.kt
Labels: ✏review, 🖥feature, 🛩develop

#222 [demo_week6] pull to refresh, 인기 키워드 추가 기능 구현
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/Extensions.kt
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/menu/popular_toolbar_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  nottokeyword/src/main/AndroidManifest.xml
  nottokeyword/src/main/java/com/example/nottokeyword/Constants.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabase.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabaseImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordModule.kt
Labels: ✅approval, 🖥feature, 🎨design, 🚖demo

#213 [develop] todo 알림 시간 관련 버그 수정
  app/src/main/java/com/gojol/notto/NottoApplication.kt
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/BaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/AlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeFinishDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeStartDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TimeStartDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
  app/src/main/res/values/strings.xml
Labels: 🐞bug, ✏review, 🛩develop

#223 [demo_week6] todo 알림 시간 관련 버그 수정
  app/src/main/java/com/gojol/notto/NottoApplication.kt
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/BaseDialog.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/AlarmPeriodDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeFinishDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/TimeStartDialog.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/util/TimeStartDialogViewModel.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
  app/src/main/res/values/strings.xml
Labels: 🐞bug, ✏review, 🚖demo

#224 [develop] 라벨 선택 다이얼로그 회전 관련 버그 수정
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
Labels: 🐞bug, ✅approval, 🛩develop

#225 [demo_week6] 라벨 선택 다이얼로그 회전 관련 버그 수정
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
Labels: 🐞bug, ✅approval, 🚖demo
