Repository boostcampwm-2021/android07-notto, pull requests merged in 2021-12, with the labels that each got.

#226 [develop] splash 화면 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/img_notto_title.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🐞bug, ✅approval, 🎨design, 🛩develop

#228 [demo_week6] splash 화면 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gojol/notto/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/img_notto_title.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🐞bug, ✏review, 🎨design, 🚖demo

#229 [develop] 홈 프래그먼트의 LayoutManager 변경
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: ✅approval, 🛩develop

#230 [demo_week6] 홈 프래그먼트의 LayoutManager 변경
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: ✅approval, 🚖demo

#227 [develop] 인기 키워드 캐싱
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/res/drawable/ic_keyword_down.xml
  app/src/main/res/drawable/ic_keyword_new.xml
  app/src/main/res/drawable/ic_keyword_up.xml
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  nottokeyword/build.gradle
  nottokeyword/src/main/AndroidManifest.xml
  nottokeyword/src/main/java/com/example/nottokeyword/Constants.kt
  nottokeyword/src/main/java/com/example/nottokeyword/Keyword.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabaseImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordModule.kt
  nottokeyword/src/main/java/com/example/nottokeyword/PlaceState.kt
  nottokeyword/src/main/java/com/example/nottokeyword/cache/CacheManager.kt
  nottokeyword/src/main/java/com/example/nottokeyword/cache/CacheManagerImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/di/KeywordModule.kt
Labels: ✅approval, 🖥feature, 🎨design, 🛩develop

#232 [demo_week6] 인기 키워드 캐싱
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/res/drawable/ic_keyword_down.xml
  app/src/main/res/drawable/ic_keyword_new.xml
  app/src/main/res/drawable/ic_keyword_up.xml
  app/src/main/res/layout/fragment_popular.xml
  app/src/main/res/layout/item_popular_keyword.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  nottokeyword/build.gradle
  nottokeyword/src/main/AndroidManifest.xml
  nottokeyword/src/main/java/com/example/nottokeyword/Constants.kt
  nottokeyword/src/main/java/com/example/nottokeyword/Keyword.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDatabaseImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordModule.kt
  nottokeyword/src/main/java/com/example/nottokeyword/PlaceState.kt
  nottokeyword/src/main/java/com/example/nottokeyword/cache/CacheManager.kt
  nottokeyword/src/main/java/com/example/nottokeyword/cache/CacheManagerImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/di/KeywordModule.kt
Labels: ✏review, 🖥feature, 🎨design, 🚖demo

#231 [develop] 알람 삭제 및 업데이트 로직 수정
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/RebootAddAlarmWorker.kt
Labels: 🐞bug, ✅approval, 🛩develop

#233 [demo_week6] 알람 삭제 및 업데이트 로직 수정
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManager.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoAlarmManagerImpl.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/RebootAddAlarmWorker.kt
Labels: 🐞bug, ✏review, 🚖demo

#238 [develop] 알림 성공/실패 버튼 터치 시 UI 동기화
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
Labels: ✏review, 🎨design, 🛩develop

#240 [demo_week6] 알림 성공/실패 버튼 터치 시 UI 동기화
  app/src/main/java/com/gojol/notto/common/Constants.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/HomeViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/dialog/RepeatTimeDialog.kt
  app/src/main/java/com/gojol/notto/util/TodoSuccessCheckBroadcastReceiver.kt
Labels: ✏review, 🎨design, 🚖demo

#241 [develop] 다크모드 디자인 수정
  app/src/main/res/values-night/themes.xml
Labels: ✏review, 🎨design, 🛩develop

#242 [demo_week6] 다크모드 디자인 수정
  app/src/main/res/values-night/themes.xml
Labels: ✏review, 🎨design, 🚖demo

#236 [develop] Option 리팩토링
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSourceImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSourceImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepositoryImpl.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
Labels: ✏review, 🖥feature, 🛩develop

#243 [demo_week6] Option 리팩토링
  app/src/main/java/com/gojol/notto/di/OptionModule.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionLocalDataSourceImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRemoteDataSourceImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/option/OptionRepositoryImpl.kt
  app/src/main/java/com/gojol/notto/ui/option/OptionViewModel.kt
Labels: ✏review, 🖥feature, 🚖demo

#239 [develop] Todo 리팩토링
  app/src/main/java/com/gojol/notto/di/TodoAlarmModule.kt
  app/src/main/java/com/gojol/notto/di/TodoLabelDatabaseModule.kt
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/model/data/todo/TodoWrapper.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSourceImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepositoryImpl.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/RebootAddAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/res/layout/activity_todo_edit.xml
Labels: 🐞bug, ✏review, 🖥feature, 🛩develop

#244 [demo_week6] Todo 리팩토링
  app/src/main/java/com/gojol/notto/di/TodoAlarmModule.kt
  app/src/main/java/com/gojol/notto/di/TodoLabelDatabaseModule.kt
  app/src/main/java/com/gojol/notto/model/data/todo/ClickWrapper.kt
  app/src/main/java/com/gojol/notto/model/data/todo/TodoWrapper.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/FakeTodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSource.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelLocalDataSourceImpl.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepository.kt
  app/src/main/java/com/gojol/notto/model/datasource/todo/TodoLabelRepositoryImpl.kt
  app/src/main/java/com/gojol/notto/ui/label/EditLabelViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditActivity.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/java/com/gojol/notto/util/RebootAddAlarmWorker.kt
  app/src/main/java/com/gojol/notto/util/SuccessButtonWorker.kt
  app/src/main/res/layout/activity_todo_edit.xml
Labels: 🐞bug, ✏review, 🖥feature, 🚖demo

#234 [develop] 인기 키워드 모듈에 Repository 패턴 적용
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/item_popular_keyword.xml
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDB.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDBImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/KeywordRepository.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/KeywordRepositoryImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/local/KeywordLocalDataSource.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/local/KeywordLocalDataSourceImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/remote/KeywordRemoteDataSource.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/remote/KeywordRemoteDataSourceImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/di/KeywordModule.kt
Labels: 🐞bug, ✏review, 🖥feature, 🛩develop

#245 [demo_week6] 인기 키워드 모듈에 Repository 패턴 적용
  app/src/main/java/com/gojol/notto/ui/popular/PopularAdapter.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularFragment.kt
  app/src/main/java/com/gojol/notto/ui/popular/PopularViewModel.kt
  app/src/main/java/com/gojol/notto/ui/todo/TodoEditViewModel.kt
  app/src/main/res/layout/item_popular_keyword.xml
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDB.kt
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDBImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/KeywordRepository.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/KeywordRepositoryImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/local/KeywordLocalDataSource.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/local/KeywordLocalDataSourceImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/remote/KeywordRemoteDataSource.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/remote/KeywordRemoteDataSourceImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/di/KeywordModule.kt
Labels: 🐞bug, ✏review, 🖥feature, 🚖demo

#246 [develop] 캘린더 캐스팅 리팩토링
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
Labels: ✏review, 🛩develop

#247 [demo_week6] 캘린더 캐스팅 리팩토링
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
Labels: ✏review, 🚖demo

#248 [develop] 버전 업그레이드
  app/build.gradle
Labels: ✏review, 🛩develop

#249 [demo_week6] 버전 업그레이드
  app/build.gradle
Labels: ✏review, 🚖demo

#251 [develop] 오프라인일 때 캐시 불러오기
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDBImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/remote/KeywordRemoteDataSourceImpl.kt
Labels: 🐞bug, ✏review, 🖥feature, 🛩develop

#252 [demo_week6] 인기 키워드 화면 오프라인 처리
  nottokeyword/src/main/java/com/example/nottokeyword/KeywordDBImpl.kt
  nottokeyword/src/main/java/com/example/nottokeyword/datasource/remote/KeywordRemoteDataSourceImpl.kt
Labels: 🐞bug, ✅approval, 🖥feature, 🚖demo

#253 [develop] 중복 라벨 처리
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature, 🛩develop

#254 [demo_week6] 라벨 중복 처리
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogFragment.kt
  app/src/main/java/com/gojol/notto/ui/label/dialog/edit/EditLabelDialogViewModel.kt
  app/src/main/res/layout/dialog_fragment_edit_label.xml
  app/src/main/res/values/strings.xml
Labels: ✏review, 🖥feature, 🚖demo

#256 [develop] 라벨 삭제 후 라벨 생성 시 순서가 꼬이는 버그 해결
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
Labels: 🐞bug, ✏review, 🛩develop

#257 [demo_week6] 라벨 삭제 후 라벨 생성 시 순서가 꼬이는 버그 해결
  app/src/main/java/com/gojol/notto/ui/label/dialog/delete/DeleteLabelDialogViewModel.kt
Labels: 🐞bug, ✅approval, 🚖demo

#258 [develop] 일부 버튼에 다크 테마 적용
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: ✏review, 🎨design, 🛩develop

#259 [demo_week6] 일부 버튼에 다크 테마 적용
  app/src/main/res/layout/activity_todo_edit.xml
  app/src/main/res/layout/item_label_list.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: ✅approval, 🎨design, 🚖demo

#255 [develop] 캘린더 리사이클러뷰 재활용, 라벨 스크롤위치 save & restore
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarViewPagerAdapter.kt
Labels: 🐞bug, ✏review, 🛩develop

#261 [demo_week6] 캘린더 리사이클러뷰 재활용, 라벨 스크롤위치 save & restore
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/CalendarFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarDayAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/calendar/adapter/CalendarViewPagerAdapter.kt
Labels: 🐞bug, ✅approval, 🚖demo

#262 [develop] fragment save state 오류 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
Labels: 🐞bug, ✏review, 🛩develop

#263 [demo_week6] fragment save state 오류 수정
  app/src/main/java/com/gojol/notto/ui/home/HomeFragment.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelAdapter.kt
  app/src/main/java/com/gojol/notto/ui/home/adapter/LabelWrapperAdapter.kt
Labels: 🐞bug, ✏review, 🚖demo

#260 [develop] README.md 주요기능 및 디자인 수정
  README.md
Labels: 📃doc, ✅approval

#264 [demo_week6] README.md 주요기능 및 디자인 수정
  README.md
Labels: 📃doc, ✏review, 🚖demo
